<?php

namespace App\AI\Services;

use App\AI\DTO\BookBrief;
use App\AI\DTO\ChapterDraft;
use App\AI\DTO\ValidationReport;
use Illuminate\Support\Facades\Log;

/**
 * Turns validated chapters into the three deliverable artifacts.
 *
 * Rendering is kept out of the agents so the book format can change without
 * touching any agent logic.
 */
class BookRenderer
{
    /**
     * @param  array<int, ChapterDraft>  $chapters
     */
    public function toMarkdown(BookBrief $brief, array $chapters): string
    {
        $parts = [];

        $parts[] = '# '.$brief->title;
        $parts[] = sprintf(
            '_A practical guide for %s._%s%sGenerated by a five-agent pipeline: '
            .'Planner, Researcher, Writer, Editor and Fact Checker. Every factual claim carries a '
            .'numbered citation, and each chapter ends with its own reference list.',
            $brief->audience,
            PHP_EOL.PHP_EOL,
            PHP_EOL
        );

        $parts[] = str_repeat('-', 3);

        foreach ($chapters as $chapter) {
            $parts[] = sprintf('## Chapter %d: %s', $chapter->chapterNumber, $chapter->title);
            $parts[] = $chapter->body;

            if ($chapter->sources !== []) {
                $parts[] = '#### References';
                foreach ($chapter->referenceLines() as $line) {
                    $parts[] = $line;
                }
            }
        }

        $parts[] = '---';
        $parts[] = sprintf(
            '_Compiled from verified public sources. URLs were checked as reachable when this book was generated._'
        );

        return implode("\n\n", $parts)."\n";
    }

    /**
     * @param  array<int, ChapterDraft>  $chapters
     */
    public function toHtml(BookBrief $brief, array $chapters): string
    {
        $e = static fn (string $value): string => htmlspecialchars($value, ENT_QUOTES | ENT_HTML5, 'UTF-8');

        $html = [];
        $html[] = '<!DOCTYPE html>';
        $html[] = '<html lang="en"><head><meta charset="utf-8">';
        $html[] = '<meta name="viewport" content="width=device-width, initial-scale=1">';
        $html[] = '<title>'.$e($brief->title).'</title>';
        $html[] = '<style>
            :root { color-scheme: light; }
            body { font-family: Georgia, "Times New Roman", serif; line-height: 1.7; max-width: 42rem;
                   margin: 3rem auto; padding: 0 1.25rem; color: #1a1a1a; background: #fff; }
            h1 { line-height: 1.25; margin-bottom: 0.25rem; }
            h2 { margin-top: 3rem; border-bottom: 1px solid #e5e5e5; padding-bottom: 0.35rem; }
            h4 { margin-top: 2rem; color: #444; font-size: 0.95rem; text-transform: uppercase;
                 letter-spacing: 0.05em; }
            .audience { color: #555; font-style: italic; }
            .prose p { margin: 0 0 1.1rem; }
            .takeaway { background: #f5f7fa; border-left: 4px solid #2b6cb0; padding: 0.85rem 1rem;
                        margin: 2rem 0; border-radius: 0 4px 4px 0; }
            .refs { font-size: 0.9rem; color: #333; }
            .refs li { margin-bottom: 0.4rem; word-break: break-word; }
            sup a { text-decoration: none; }
            a { color: #2b6cb0; }
            hr { border: 0; border-top: 1px solid #e5e5e5; margin: 3rem 0; }
            footer { color: #666; font-size: 0.85rem; margin-top: 3rem; }
        </style></head><body>';

        $html[] = '<h1>'.$e($brief->title).'</h1>';
        $html[] = '<p class="audience">A practical guide for '.$e($brief->audience).'.</p>';
        $html[] = '<hr>';

        foreach ($chapters as $chapter) {
            $html[] = '<h2>Chapter '.$chapter->chapterNumber.': '.$e($chapter->title).'</h2>';
            $html[] = '<div class="prose">'.$this->bodyToHtml($chapter->body).'</div>';

            if ($chapter->sources !== []) {
                $html[] = '<h4>References</h4><ol class="refs">';
                foreach ($chapter->sources as $source) {
                    $html[] = '<li value="'.$source->citationId.'">'
                        .$e($source->organization).'. &ldquo;'.$e($source->title).'&rdquo;. '
                        .'<a href="'.$e($source->url).'" rel="noopener noreferrer">'.$e($source->url).'</a>'
                        .'</li>';
                }
                $html[] = '</ol>';
            }
        }

        $html[] = '<hr><footer>Compiled from verified public sources. URLs were checked as reachable '
            .'when this book was generated.</footer>';
        $html[] = '</body></html>';

        return implode("\n", $html)."\n";
    }

    /**
     * Convert chapter Markdown-ish prose into paragraphs, rendering [n] markers
     * as superscript links into the chapter reference list.
     */
    private function bodyToHtml(string $body): string
    {
        $takeaway = null;

        if (preg_match('/^\s*Takeaway:\s*(.+)$/mi', $body, $m) === 1) {
            $takeaway = trim($m[1]);
            $body = str_replace($m[0], '', $body);
        }

        $body = preg_replace('/^\s*(?:#{1,6}\s*)?References\s*:?\s*$.*/ms', '', $body) ?? $body;

        $paragraphs = preg_split('/\R{2,}/', trim($body)) ?: [];
        $html = '';

        foreach ($paragraphs as $paragraph) {
            $paragraph = trim($paragraph);
            if ($paragraph === '') {
                continue;
            }

            $html .= '<p>'.$this->inline($paragraph).'</p>';
        }

        if ($takeaway !== null) {
            $html .= '<div class="takeaway"><strong>Takeaway:</strong> '
                .$this->inline($takeaway).'</div>';
        }

        return $html;
    }

    private function inline(string $text): string
    {
        $e = static fn (string $v): string => htmlspecialchars($v, ENT_QUOTES | ENT_HTML5, 'UTF-8');

        $text = $e($text);

        // Linkify bare URLs, leaving citation markers alone.
        $text = preg_replace(
            '#(https?://[^\s<"]+)#',
            '<a href="$1" rel="noopener noreferrer">$1</a>',
            $text
        ) ?? $text;

        return preg_replace('/\[(\d+)\]/', '<sup>[$1]</sup>', $text) ?? $text;
    }

    /**
     * Write all three artifacts to the configured output directory.
     *
     * @param  array<int, ChapterDraft>  $chapters
     * @return array<string, string> path => written path
     */
    public function writeArtifacts(BookBrief $brief, array $chapters, ValidationReport $report): array
    {
        $dir = (string) config('ai.workflow.output_dir');

        if (! is_dir($dir) && ! mkdir($dir, 0775, true) && ! is_dir($dir)) {
            Log::error('[Renderer] could not create output directory', ['dir' => $dir]);
        }

        $paths = [];

        $markdown = $dir.DIRECTORY_SEPARATOR.'book.md';
        file_put_contents($markdown, $this->toMarkdown($brief, $chapters));
        $paths['book.md'] = $markdown;

        $html = $dir.DIRECTORY_SEPARATOR.'book.html';
        file_put_contents($html, $this->toHtml($brief, $chapters));
        $paths['book.html'] = $html;

        $json = $dir.DIRECTORY_SEPARATOR.'validation-report.json';
        file_put_contents($json, json_encode($report->toArray(), JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES)."\n");
        $paths['validation-report.json'] = $json;

        Log::info('[Renderer] artifacts written', [
            'paths' => array_map('basename', $paths),
            'passed' => $report->passed,
        ]);

        return $paths;
    }
}